### ISSUE TITLE
Add eslint-plugin-nuxt to default config

### ISSUE THREAD

**Issue by manniL** [nuxt/eslint#101]

**Comment by nathanchase** [comment]
#https://github.com/nuxt/eslint-plugin-nuxt/issues/110

**Comment by nathanchase** [comment]
Related issue: nuxt/eslint-plugin-nuxt#110

**Comment by nathanchase** [comment]
I would think that [@nuxtjs/eslint-module](https://github.com/nuxt-community/eslint-module) could be the single point of dependency, automatically including:

"@nuxtjs/eslint-config": "^3.0.0",
"babel-eslint": "^10.1.0",
"eslint": "^7.2.0",
"eslint-plugin-nuxt": "^1.0.0",

Then, you'd just have a single dependency in a `create-nuxt-app`. So instead of:

```js
"devDependencies": {
    "@nuxtjs/eslint-config": "^3.0.0",
    "@nuxtjs/eslint-module": "^2.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^7.2.0",
    "eslint-plugin-nuxt": "^1.0.0",
  }
```
You'd just have:
```js
"devDependencies": {
    "@nuxtjs/eslint-module": "^2.0.0",
  }
```
or whichever package is the most encompassing as "Nuxt recommended defaults"?

**Comment by antfu** [comment]
`eslint-plugin-nuxt`'s rules are mostly for Nuxt 2 and most of them are no longer useful in Nuxt 3. We had the new `@nuxt/eslint-plugin` introduced in #332, which is included in the new eslint-config. Consider this is resolved.
